version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - {image: 'circleci/golang:1.12'}
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - {run: 'mkdir -p $TEST_RESULTS'}
      - {restore_cache: {keys: ['go-mod-v4-{{ checksum "go.sum" }}']}}
  test:
    -
      run: null
      name: 'Run tests'
      command: "cd api\ngo test -coverprofile=c.out\ngo tool cover -html=c.out -o coverage.html\nmv coverage.html /tmp/test-results\n"
    -
      save_cache: {key: 'go-mod-v4-{{ checksum "go.sum" }}', paths: [/go/pkg/mod]}
    -
      store_artifacts: {path: /tmp/test-results, destination: raw-test-output}
    -
      store_test_results: {path: /tmp/test-results}
    -
      codecov/upload: {file: /tmp/test-results}
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
      - test
