// Code generated by MockGen. DO NOT EDIT.
// Source: services/workflow.go

// Package interfaces is a generated GoMock package.
package interfaces

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/hbalmes/ci_cd-api/api/models"
	webhook "github.com/hbalmes/ci_cd-api/api/models/webhook"
	apierrors "github.com/hbalmes/ci_cd-api/api/utils/apierrors"
	reflect "reflect"
)

// MockWorkflowService is a mock of WorkflowService interface
type MockWorkflowService struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowServiceMockRecorder
}

// MockWorkflowServiceMockRecorder is the mock recorder for MockWorkflowService
type MockWorkflowServiceMockRecorder struct {
	mock *MockWorkflowService
}

// NewMockWorkflowService creates a new mock instance
func NewMockWorkflowService(ctrl *gomock.Controller) *MockWorkflowService {
	mock := &MockWorkflowService{ctrl: ctrl}
	mock.recorder = &MockWorkflowServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockWorkflowService) EXPECT() *MockWorkflowServiceMockRecorder {
	return m.recorder
}

// SetWorkflow mocks base method
func (m *MockWorkflowService) SetWorkflow(config *models.Configuration) apierrors.ApiError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWorkflow", config)
	ret0, _ := ret[0].(apierrors.ApiError)
	return ret0
}

// SetWorkflow indicates an expected call of SetWorkflow
func (mr *MockWorkflowServiceMockRecorder) SetWorkflow(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWorkflow", reflect.TypeOf((*MockWorkflowService)(nil).SetWorkflow), config)
}

// UnsetWorkflow mocks base method
func (m *MockWorkflowService) UnsetWorkflow(config *models.Configuration) apierrors.ApiError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsetWorkflow", config)
	ret0, _ := ret[0].(apierrors.ApiError)
	return ret0
}

// UnsetWorkflow indicates an expected call of UnsetWorkflow
func (mr *MockWorkflowServiceMockRecorder) UnsetWorkflow(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsetWorkflow", reflect.TypeOf((*MockWorkflowService)(nil).UnsetWorkflow), config)
}

// CheckWorkflow mocks base method
func (m *MockWorkflowService) CheckWorkflow(config *models.Configuration, prWebhook *webhook.PullRequestWebhook) *webhook.Status {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckWorkflow", config, prWebhook)
	ret0, _ := ret[0].(*webhook.Status)
	return ret0
}

// CheckWorkflow indicates an expected call of CheckWorkflow
func (mr *MockWorkflowServiceMockRecorder) CheckWorkflow(config, prWebhook interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckWorkflow", reflect.TypeOf((*MockWorkflowService)(nil).CheckWorkflow), config, prWebhook)
}
